server:
  port: 8002
#服务名称
spring:
  application:
    name: Order-Service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car_server?serverTimezone=GMT%2B8
    username: root
    password: zxy6
  cloud:
    nacos:
      server-addr: localhost:8848