server:
  port: 8005
#服务名称
spring:
  redis:
    host: 192.168.170.128
    database: 1
    password: zxy666
  application:
    name: Admin-Service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car_server?serverTimezone=GMT%2B8
    username: root
    password: zxy6
  cloud:
    nacos:
      server-addr: localhost:8848